version: '3.9'

services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'root'
    volumes:
      - ../db:/var/lib/mysql
      - ../db_import:/db_import
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:6.6.2
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PHP_EXTENSION_XDEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - ../wp-core:/var/www/html/
      - ../plugins:/var/www/html/wp-content/plugins
      - ../themes:/var/www/html/wp-content/themes
      - ../uploads:/var/www/html/wp-content/uploads
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
      - db
    volumes_from:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    user: xfs
    entrypoint: wp
    command: --info